import React from 'react'

const PLStatement = () => {
  return (
    <div>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, quaerat dolores. Blanditiis eaque ut, laboriosam dolore, eveniet labore eum dignissimos magni omnis pariatur ad. Ratione doloremque, aut expedita, ducimus eius culpa, impedit numquam fugit quos sunt neque alias obcaecati! Ut modi, in vero omnis, eaque totam doloremque nesciunt facere ullam odit aliquid sit quidem perferendis quibusdam enim accusamus cumque. Totam beatae earum quasi aspernatur illo, expedita ab eius voluptas possimus, nulla velit dolores repudiandae ratione aperiam aliquid quos modi? Nostrum aliquid ipsam est explicabo dolorum quo illo velit fuga, atque voluptatibus possimus voluptatem inventore in architecto nulla quisquam ab aspernatur dignissimos eligendi iure. Neque quae accusamus dolore, ipsum id voluptates cupiditate fugit ab possimus consequuntur, natus voluptatem explicabo veniam ducimus ad a officiis voluptatibus hic debitis dicta deserunt fugiat labore reiciendis laborum. Explicabo nostrum impedit commodi harum praesentium perferendis, eos animi minus, eius doloremque facilis illo id sapiente quod totam ipsa iste quo perspiciatis veritatis corrupti soluta possimus! Saepe nesciunt in perspiciatis nostrum maiores beatae veniam consequuntur eaque unde perferendis, laudantium molestiae quam quibusdam consectetur maxime, architecto blanditiis sunt. Porro aspernatur dolor, alias nulla necessitatibus ratione harum optio, vel, iure recusandae reiciendis? Adipisci cupiditate a, incidunt aspernatur totam ab id natus nam, animi odit ipsa sit mollitia voluptate reprehenderit quidem, quas officia consequuntur ut hic unde tenetur placeat sequi. Autem ut maxime tempora obcaecati magnam nihil minima blanditiis ducimus voluptatibus et nobis accusantium nemo rem quidem quo nam veritatis provident aliquam, ullam qui? Possimus, sit. Quis eligendi consequuntur beatae, in eveniet alias velit deleniti deserunt consectetur reprehenderit rerum aspernatur soluta officiis inventore sint porro vel corrupti voluptatibus dicta voluptas, facere, ut perferendis pariatur! In nam deleniti debitis obcaecati veniam, a blanditiis sit voluptatum necessitatibus mollitia architecto? Cumque commodi, ipsam, ut officiis porro sapiente esse voluptatum deleniti excepturi hic nesciunt labore suscipit vero magni reiciendis aperiam nulla dolor ipsa eum voluptates vel, voluptatem itaque. Incidunt dolorum mollitia voluptas itaque consequuntur voluptatem debitis sunt quidem unde aperiam laborum, delectus eos vel beatae harum ad iste ratione voluptatum expedita totam aspernatur exercitationem! Reiciendis laborum temporibus mollitia necessitatibus.z
      
    </div>
  )
}

export default PLStatement
